name: Auto-comment on new issues and pull requests
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Add comment for new issue or pull request
        uses: actions-ecosystem/action-create-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
          body: |
            ${{ github.event_name == 'issues' && 'Thank you @' || '' }}${{ github.event.issue.user.login || github.event.pull_request.user.login }}${{ github.event_name == 'issues' && ' for bringing up this issue to help enhance our project even further! We\'ll review it soon. 🙌❤️' || ' for opening a pull request. We\'ll review it as soon as possible 🙌❤️' }}
